users_index:
    path:     /
    defaults: { _controller: "Gdr3625BackofficeBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "Gdr3625BackofficeBundle:Users:show" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "Gdr3625BackofficeBundle:Users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "Gdr3625BackofficeBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "Gdr3625BackofficeBundle:Users:delete" }
    methods:  DELETE
