Gdr3625\BackofficeBundle\Entity\Equipes_Publications:
    type: entity
    table: null
    repositoryClass: Gdr3625\BackofficeBundle\Repository\Equipes_PublicationsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idPublications:
            type: integer
            column: id_publications
        idEquipes:
            type: integer
            column: id_equipes
    lifecycleCallbacks: {  }
