<?php

namespace Gdr3625\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Equipes_KeywordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Equipes_KeywordsRepository extends EntityRepository
{
}
