<?php

namespace Gdr3625\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Equipes_BrevetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Equipes_BrevetsRepository extends EntityRepository
{
}
