<?php

namespace Gdr3625\BackofficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FluxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxRepository extends EntityRepository
{
}
